INSERT INTO CARGO(ID, NAME, WEIGHT, ENTITY_TYPE, CLOTHERS_SIZE, CLOTHERS_MATERIAL) VALUES (
  1, 'JEANS', 200, 'CLOTHERS', 'XXL', 'COTTON'
);

INSERT INTO CARGO(ID, NAME, WEIGHT, ENTITY_TYPE, FOOD_EXPIRATION_DATE, FOOD_STORE_TEMPERATURE) VALUES (
  2, 'APPLE', 300, 'FOOD', parsedatetime('20-09-2025 18:47', 'dd-MM-yyyy hh:mm'), 800
);

INSERT INTO CARGO(ID, NAME, WEIGHT, ENTITY_TYPE, FOOD_EXPIRATION_DATE, FOOD_STORE_TEMPERATURE) VALUES (
  3, 'ORANGE', 300, 'FOOD', parsedatetime('20-09-2055 18:47', 'dd-MM-yyyy hh:mm'), -20
);

INSERT INTO CARRIER VALUES (4, 'Carrier_1', 'Spb', 'PLANE');
INSERT INTO CARRIER VALUES (5, 'Carrier_1', 'Msc', 'SHIP');
INSERT INTO CARRIER VALUES (6, 'Carrier_1', 'Spb', 'PLANE');

INSERT INTO TRANSPORTATION VALUES (7, 1, 4, 'Fast', 'Ivan', parsedatetime('20-09-2025 18:47', 'dd-MM-yyyy hh:mm'));
INSERT INTO TRANSPORTATION VALUES (8, 2, 5, 'Slow', 'Petr', parsedatetime('20-09-2025 18:47', 'dd-MM-yyyy hh:mm'));

